name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3

      - run: dotnet restore

      - run: dotnet build *.sln --no-restore -c Release

      - run: dotnet test --no-build

      - run: dotnet pack *.sln --no-build --output .
