name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
      pull-requests: write

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3

      - run: dotnet restore

      - run: dotnet build *.sln --no-restore

      - run: dotnet test

      - run: dotnet pack *.sln --no-build --output .
